[project]
name = "test-task"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.30.0",
    "fastapi[standard]>=0.117.1",
    "lxml>=6.0.2",
    "sqlalchemy[postgresql-asyncpg]>=2.0.43",
]
